<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albums [
    <!ELEMENT albums (album)*>
    <!ELEMENT album (name,artist,tracks+,price?)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT tracks (track)+>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT track (#PCDATA)>
]>
<albums>
    <album>
        <name>Kop kop kop</name>
        <artist>Kake Randelin</artist>
        <tracks>
            <track>Track 1</track>
            <track>Track 2</track>
            <track>Track 3</track>
        </tracks>
        <price>69,99</price>
    </album>
    <album>
        <name>Kiikun kaakun</name>
        <artist>Jope Ruonansuu</artist>
        <tracks>
            <track>Track 1</track>
        </tracks>
    </album>
</albums>