=== antonwis/opendata_vue/teht9.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="kappa" xmlns="kappa" elementFormDefault="qualified">

    <xs:element name="albums">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="album" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="album">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" ref="name" />
                <xs:element minOccurs="1" maxOccurs="1" ref="artist" />
                <xs:element ref="tracks" />
                <xs:element minOccurs="0" ref="price" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="name" type="xs:string"/>
    <xs:element name="artist" type="xs:string"/>
    <xs:element name="tracks">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="track" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="track" type="xs:string"/>
    <xs:element name="price" type="xs:string"/>

</xs:schema>

=== antonwis/opendata_vue/teht9.xml
<?xml version="1.0" encoding="UTF-8"?>
<albums xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="kappa" xsi:schemaLocation="kappa teht9.xsd">
    <album>
        <name>Kop kop kop</name>
        <artist>Kake Randelin</artist>
        <tracks>
            <track>Track 1</track>
            <track>Track 2</track>
            <track>Track 3</track>
        </tracks>
        <price>69,99</price>
    </album>
    <album>
        <name>Kiikun kaakun</name>
        <artist>Jope Ruonansuu</artist>
        <tracks>
            <track>Track 1</track>
        </tracks>
    </album>
</albums>
